# Generated by Django 2.2.3 on 2019-07-14 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translator',
            name='Email',
        ),
        migrations.AlterField(
            model_name='translator',
            name='CardNum',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=11, null=True, unique=True),
        ),
    ]
