# Generated by Django 2.1 on 2019-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='ProfileImage',
        ),
        migrations.AddField(
            model_name='client',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='profile_img/no-img.jpg', upload_to='profile_img/'),
        ),
        migrations.AddField(
            model_name='translator',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='profile_img/no-img.jpg', upload_to='profile_img/'),
        ),
    ]
