# Generated by Django 2.1 on 2019-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20190729_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ProfileImage',
            field=models.ImageField(blank=True, default='profile_img/no-img.jpg', upload_to='profile_img/'),
        ),
    ]
