# Generated by Django 2.1 on 2019-07-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_customuser_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ProfileImage',
        ),
        migrations.RemoveField(
            model_name='translator',
            name='ProfileImage',
        ),
    ]
