# Generated by Django 2.2.3 on 2019-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=20)),
                ('Last_name', models.CharField(default='', max_length=20)),
                ('User_name', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(default='', max_length=20)),
                ('Last_name', models.CharField(default='', max_length=20)),
                ('User_name', models.CharField(default='', max_length=30)),
                ('Password', models.CharField(default='', max_length=20)),
                ('Card_num', models.IntegerField()),
            ],
        ),
    ]
