# Generated by Django 2.2.3 on 2019-07-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='client',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Client'),
        ),
        migrations.AddField(
            model_name='documents',
            name='translator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Translator'),
        ),
        migrations.AlterField(
            model_name='client',
            name='User_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='translator',
            name='User_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
