# Generated by Django 2.2.3 on 2019-07-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190710_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='client',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Client'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='translator',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Translator'),
        ),
    ]
