# Generated by Django 2.2.3 on 2019-07-10 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20190710_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='First_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='User_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='client',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Client'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='documents',
            name='translator',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='web.Translator'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='Card_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='translator',
            name='First_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='translator',
            name='Last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='translator',
            name='Password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='translator',
            name='User_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
