# Generated by Django 2.2.3 on 2019-07-13 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0005_auto_20190710_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='client',
            old_name='First_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='User_name',
            new_name='User_Name',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='Card_num',
            new_name='Card_Num',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='First_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='Last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='translator',
            old_name='User_name',
            new_name='User_Name',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
